sudo: required
services:
  - docker
language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly

script:
    - export RUST_VERSION=$TRAVIS_RUST_VERSION
    - echo $RUST_VERSION $TRAVIS_RUST_VERSION
    - _build/run_build.sh
after_success:
    - _build/push-to-docker-hub.sh
