FROM ekidd/rust-musl-builder
MAINTAINER xliiv "tymoteusz.jankowski@gmail.com"

ARG REDIS_IP
RUN echo $REDIS_IP
# valid options: stable, beta, nightly
ARG RUST_VERSION=stable
RUN echo $RUST_VERSION

ADD . ./

RUN rustup default $RUST_VERSION
RUN rustup target add x86_64-unknown-linux-musl
RUN cargo build --release --verbose
RUN DASHBOARD_REDIS_IP_PORT=$REDIS_IP:6379 cargo test --release

# npm & bower stuff
RUN sudo apt update && sudo apt install -y \
    nodejs \
    npm
RUN sudo ln -s "$(which nodejs)" /usr/bin/node
RUN sudo npm install -g bower
RUN cd src/static && sudo bower install --allow-root