FROM alpine:3.5
MAINTAINER xliiv "tymoteusz.jankowski@gmail.com"

ARG APP_PATH=_build/dashboard
ARG BOWER_COMPONENTS=_build/bower_components

ADD dashboard.env .
ADD src/templates/ src/templates/
ADD src/static/ src/static/
ADD $BOWER_COMPONENTS src/static/bower_components
ADD $APP_PATH dashboard

CMD ./dashboard
